name: RDP via GitHub Actions
on: workflow_dispatch

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          # Set password (change 'YourPassword123!' to your own)
          $password = "YourPassword123!"
          net user Administrator $password

          # Enable RDP
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          # Install & Configure Ngrok (replace YOUR_NGROK_TOKEN)
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath .
          ./ngrok authtoken 2icja6dYBnM1LQR9ebeZkWUvVTf_4MRfj8crhi117JXZ8ieW1
          ./ngrok tcp 3389 --log=stdout > ngrok.log &

          # Wait for Ngrok to start and extract the public URL
          Start-Sleep -Seconds 10
          $ngrok_url = (Get-Content ngrok.log | Select-String -Pattern "tcp.ngrok.io.*" | Select-Object -First 1).ToString().Split(" ")[-1]
          
          # Save connection details
          echo "RDP Address: $ngrok_url" > rdp_info.txt
          echo "Username: Administrator" >> rdp_info.txt
          echo "Password: $password" >> rdp_info.txt

      - name: Upload RDP Connection Info
        uses: actions/upload-artifact@v4
        with:
          name: rdp-connection-details
          path: rdp_info.txt

      - name: Keep Session Alive
        run: |
          # Keep the VM running for 6 hours (GitHub's max job duration)
          Start-Sleep -Seconds 21600
